# Generated by Django 4.2.3 on 2023-08-05 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('propic', models.FileField(default='anonymous.png', upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=50)),
                ('departments', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('doc_image', models.FileField(default='anonymous.jpg', upload_to='media/')),
                ('doc_desc', models.TextField(max_length=500)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_doctor.doc_user')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
