# Generated by Django 4.2.3 on 2023-08-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0002_rename_prp_price_product_pro_price'),
        ('app_buyer', '0002_user_propic'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buyer.user')),
                ('prd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seller.product')),
            ],
        ),
    ]
